### ISSUE TITLE
how to create the nsynth_features folder?

### ISSUE THREAD

**Issue by sck** [zafarrafii/CQHC-Python#1]
Hi,

thank you so much for making this repository!   While going through the notebooks I noticed that 
I don't know how to create the folder nsynth_features for notes.ipynb.  I downloaded the nsynth dataset, but it doesn't contain a nsynth_features folder in the right format.   Did I overlook some  documentation?

**Comment by zafarrafii** [comment]
Hi Sven,

Sorry for not making this clear, I didn't think someone would try to replicate this work :) The NSynth dataset only contains the musical notes (separated in 3 subfolders, for training, validation, and testing). You need to create you own nsynth_features folder and compute the features (MFCCs and CQT-SECs) yourself. You can use the cqtsec module for that. I didn't include the folder with the computed features in this repo because it's too large. The notebook notes.ipynb has a section that shows an example for computing those features for one specific velocity (75): https://nbviewer.jupyter.org/github/zafarrafii/CQT-SEC-Python/blob/master/notes.ipynb#3A Hope this helps!

Best,

Zafar
